### PR TITLE
Update compile SDK from 29 (Android 10) to 30 (Android 11)

### PR DESCRIPTION
**Pull request by oliverlockwood**
Based on https://developer.android.com/about/versions/11/behavior-changes-all I think this should be fine (we've already improved our approach around permissions in a relevant way).

Based on https://developer.android.com/about/versions/11/behavior-changes-11 I am **not** yet upgrading the target SDK - since I think the statement of:
> Scoped storage enforcement: Access into external storage directories is limited to an app-specific directory and specific types of media that the app has created.

has a potential impact until Jez's work on the offline mapping download has been completed.

@jezhiggins @mvl22 @HilaryN please review.

### CODE REVIEW

**Comment by jezhiggins** [comment]
The scoped file access is already in hand, so there's no need to hold back because of that.

**Comment by oliverlockwood** [comment]
> The scoped file access is already in hand, so there's no need to hold back because of that.

As in, already merged in, or already in your PR which is outstanding?

**Comment by jezhiggins** [comment]
In the outstanding PR.

**Comment by HilaryN** [comment]
Looks good to me. Not sure if it's a relevant test but I quickly checked voice nav works when screen locked for Android 11, 10 and 9 emulators.

**Comment by oliverlockwood** [comment]
On that basis @jezhiggins I'll keep that change out of this PR, so we can merge this in without waiting for yours to be ready.  I've raised #445 and #446 to track the outstanding dependency upgrade bits; if you would be so kind to review as it stands, that'd be great.

**Review by jezhiggins — APPROVED** [review]

**Pull request merged**
