### PR TITLE
Change the lock-screen-on button

### PR DESCRIPTION
**Pull request by oliverlockwood**
Connects to #42.

## In the previous public release, the LiveRide screen stay-alive button looked like this:
screen shot 2018-07-23 at 09 40 57
screen shot 2018-07-23 at 09 41 05

## In the current beta, it looks like this:
screen shot 2018-07-23 at 09 35 54
screen shot 2018-07-23 at 09 36 02

## After this PR:
screen shot 2018-08-30 at 11 29 44
screen shot 2018-08-30 at 11 29 51

### CODE REVIEW

**Comment by oliverlockwood** [comment]
@si-the-pie @mvl22 please review this with the context of wanting to get the new release 3.6 out!

**Comment by si-the-pie** [comment]
The green coloured outline padlock is a subtle distinction from the gray outline padlock, especially outdoors.
Can I suggest that the eye image (called `visibility` in the material icons listing) is used instead of the green padlock.
Colour it green if you want. This should be an improvement on the current position.

Another issue is that it takes two taps to change the initial state. The first tap is detected as the button flickers but does not change state.

(As tested with version 1505.)

**Comment by oliverlockwood** [comment]
@si-the-pie are you saying it should be the `lock_open` image when disabled, and the `visibility` icon when enabled?  To my mind that would make things even less clear.

@mvl22 ?

**Comment by si-the-pie** [comment]
The button is really there to turn off screen timeout. [I originally suggested](https://github.com/cyclestreets/android/issues/42#issuecomment-416972762) that a tool tip briefly appears to explain the new state, i.e. 'Screen will stay on' or 'Screen will timeout'.

Can you tell us whether it is possible to have such tool tip?

If a tool tip is available then that would help unravel what this button is doing. The button must have two quite distinct images so that it can easily be discerned when looking at the screen from a distance.

Looking through the material icons how about:

- `timer` for the _Screen will timeout_
- `visibility` for _Screen will stay on_

These are quite distinct, but need the tooltip to avoid confusion.

I am making these suggestions within the constraints of a workaround rather than [another design](https://github.com/cyclestreets/android/issues/42#issuecomment-417097332).

**Comment by mvl22** [comment]
> eye image

I agree with Oliver that this is even less clear.

The proper solution here is a label, as I don't think any icon on its own will be enough. As Oliver suggested, I think that should go in the next release rather than hold this up here. There is a *lot* going into this 3.6 release and I really want to get it out the door.

**Pull request merged**
