### PR TITLE
391: New compass icon for map rotation in LiveRide

### LINKED ISSUE #391: (Optionally) rotate the map with travel direction in LiveRide
We occasionally get feedback about this, e.g. the following excerpt from a review:
>Would be better if the map rotated with travel direction

A brief search on the internet threw up this page: https://stackoverflow.com/questions/37575522/osmdroid-how-to-rotate-osm-map-as-per-devices-direction which suggests this isn't too infeasible to achieve; bearing in mind we're currently on the latest version of osmdroid it's probably worth having a go.

### PR DESCRIPTION
**Pull request by oliverlockwood**
If accepted, I believe this will finish and close #391.

This makes use of the SVG kindly provided by @si-the-pie, with some theming for enabled/disabled to match what we use in the app.

Seeing as how pictures are worth a thousand words, I've just pasted screenshots running in the emulator, before and after, with and without highlighting.  I turned on the lock-screen-on button as well for comparison.

## Before
Screen Shot 2020-05-13 at 07 04 28 Screen Shot 2020-05-13 at 07 04 36

## After

Screen Shot 2020-05-13 at 06 57 02 Screen Shot 2020-05-13 at 06 57 20

Note that we can't make the icon any bigger inside the floating action button (as FABs have a deliberate white boundary around them).

Feedback please @jezhiggins, @mvl22 and others if you care to?

### CODE REVIEW

**Comment by jezhiggins** [comment]
That is lovely.

**Comment by mvl22** [comment]
Does it need the extra green ring? It looks very small to me, and that green ring just feels like visual clutter.

**Comment by si-the-pie** [comment]
> Does it need the extra green ring? It looks very small to me, and that green ring just feels like visual clutter. I realise it's to get the feeling of a compass. Can the green ring maybe be thinner, or just replace the ring with a slightly shaded background.

I agree the green ring doesn't appear to be necessary and I can make a new SVG without it, expanding the needle to take up the rest of the space.

**Comment by oliverlockwood** [comment]
@si-the-pie no need to submit an updated SVG, I can easily enough manually remove those bits from the XML, I think :)

**Comment by oliverlockwood** [comment]
Here's what it looks like with the rings removed (latest commit, just pushed):

Screen Shot 2020-05-13 at 13 58 40 Screen Shot 2020-05-13 at 13 59 01

**Comment by oliverlockwood** [comment]
What do you think now @mvl22 @si-the-pie @jezhiggins ?

**Comment by oliverlockwood** [comment]
plausibly we could get it slightly expanded with a different view box (I removed the ring and set the view box to `100:799`
see
https://raw.githubusercontent.com/cyclestreets/android/391-use-new-compass-icon/assets/compass.svg

but I didn't know how far to push it - so maybe we do need your SVG fu, @si-the-pie  😄

**Comment by mvl22** [comment]
That looks much better, and clear as it is.

**Comment by oliverlockwood** [comment]
OK here's two more pairs of options:

## (A) with some more zooming in just by me changing the viewBox:
Screen Shot 2020-05-13 at 14 13 42 Screen Shot 2020-05-13 at 14 13 37

## (B) using @si-the-pie's updated SVG (which makes it more pointy)
Screen Shot 2020-05-13 at 14 21 23 Screen Shot 2020-05-13 at 14 21 30

I'm open minded.  What's your choice, @mvl22 @jezhiggins @si-the-pie ?

**Comment by mvl22** [comment]
Colourful and larger is better. This is a UI people are using with their eye a metre away while cycling.

**Comment by oliverlockwood** [comment]
(Colour is a product of whether or not it's been clicked "on".)
I also prefer the broader one, so that's what this PR now does as things stand.

As soon as someone has reviewed & approved this, it can be merged and the beta builds updated.

**Comment by oliverlockwood** [comment]
Merging without an official review approval on Github, because everyone seems happy with where things stand.

**Pull request merged**
