### PR TITLE
Request audio focus for LiveRide directions

### LINKED ISSUE #104: LiveRide does not mute other audio
When LiveRide is giving instructions then the audio should be focused with something like [requestAudioFocus](http://developer.android.com/reference/android/media/AudioManager.html#requestAudioFocus%28android.media.AudioManager.OnAudioFocusChangeListener,%20int,%20int%29).

Thanks

### PR DESCRIPTION
**Pull request by oliverlockwood**
Closes #104.

### CODE REVIEW

**Comment by oliverlockwood** [comment]
Right, this is now ready for review; I've successfully tested it on my phone (which is running Marshmallow).

@jezhiggins is there any chance of you live testing this on your phone, please? I recall you're running Oreo, and the code pathway is different for Oreo and above!  (I'm happy for you to manually test this branch, or merge and then test the beta build, as you prefer.)

**Comment by jezhiggins** [comment]
No problem - I'll give it a spin today.

**Comment by oliverlockwood** [comment]
@jezhiggins I believe it depends on how the other app (music player or whatever) handles the audio focus change request.  It should be either turned down or paused (frankly, I don't particularly mind which) while the navigation speech is happening.

**Comment by jezhiggins** [comment]
Tried two things which both turned down, tried a third which paused. So, yes, it's all working.

**Pull request merged**
