### PR TITLE
Do CI builds on Travis

### PR DESCRIPTION
**Pull request by oliverlockwood**
This change should allow us to build the signed APK in CI on Travis (which we already use for PR builds).  The intention being that we would no longer need to use Jez's private build server for the CycleStreets Android app.

All the secret data is encrypted according to https://docs.travis-ci.com/user/encrypting-files/, so that only Travis can decrypt it.  (Note that we still need to keep a safe copy of our signing information elsewhere, in case we ever move away from using Travis for our builds.)

If people are generally happy with this approach, I would propose the next steps as:
-  merge this, and then I'll do some verification work on the signing of the APK etc.
-  decide how we publish the built artifacts
    -  we could copy them onto a server somewhere (as is done by the existing Jenkins builds), or...
    -  (my preference) we could just tackle #179, and publish them as open beta builds.

 @mvl22 and @jezhiggins, your thoughts please?

### CODE REVIEW

**Comment by mvl22** [comment]
Open beta builds (do they end up here on GitHub?) are good. :)

**Comment by jezhiggins** [comment]
Yea, like it and am happy to merge.  A rather cool next step (but please don't interpret this as any kind of instruction) would be to push the signed builds directly up to the Play Store as an alpha or beta build.

**Comment by oliverlockwood** [comment]
Good stuff.  I just fixed the bash errors (thanks Travis for checking my PR quality!) and I think this is good to be merged.

@jezhiggins @mvl22 we're all in accord then: push signed builds directly up to the Play Store as alpha/beta.
However I'm stuck, because I need access to the Google Developer Console.  Although Jez shared with me the password a while back, Google's security is wanting more verification than that, as follows:

screen shot 2017-05-24 at 21 07 59

I'll be in touch less publicly to work through this with you.

**Comment by oliverlockwood** [comment]
I'm aware that the CI build failed as it tried to decrypt one of the license files.  I'll try and look at this tomorrow.

**Comment by oliverlockwood** [comment]
FYI, build https://travis-ci.org/cyclestreets/android/builds/236041036 is running now and looks like it's successfully done the license decryption phase.  I committed https://github.com/cyclestreets/android/commit/23e96efefcfe754bf694996441c4bd6804a4c98e straight to master to fix this.

**Pull request merged**
