### PR TITLE
Fixing build warnings etc.

### PR DESCRIPTION
**Pull request by oliverlockwood**
I thought that before working on a more significant PR I'd get myself into the swing of things by fixing some low-hanging fruit.  This PR does the following:
-  Remove redundant modifier `static` on inner interfaces
-  Remove redundant modifier `public` for interface methods
-  Remove unnecessary `final` declaration on `static` and/or `private` methods
-  Remove redundant `private` modifier for enum constructors
-  Remove pointless boolean expressions
-  Remove unused imports
-  Collapse identical `catch` blocks
-  Use diamond operator
-  Remove redundant type cast

### CODE REVIEW

**Comment by mvl22** [comment]
Oliver - thanks very much for this!

@jezhiggins, could you review and merge?

**Comment by jezhiggins** [comment]
Quick scan through looks good - thanks!  Will come back and merge over the weekend.

**Comment by oliverlockwood** [comment]
Glad to help 👍

**Comment by oliverlockwood** [comment]
@jezhiggins did you have a chance to look into whether anything more needs doing on this PR?

**Pull request merged**
