### PR TITLE
Fix permissions for LiveRide, and generally improve how we request permissions.

### LINKED ISSUE #429: Enable voice navigation even when screen timed out
User request:

"recently discovered your awesome android app! A small q - do you know how to make the voice navigation keep working even if the screen timesout? If I force the screen on it works - but then drains battery quite quickly."

https://twitter.com/sim0nw/status/1273872031864500229

### PR DESCRIPTION
**Pull request by oliverlockwood**
Closes #429, #411.

Supercedes #438.

The idea of this is to:
- take what @HilaryN figured out in #438 and apply that (the first commit)
- improve the "justification" screens that give context for why we're asking for permissions, by:
   - making the text clearer and more thorough
   - always including them (including before first attempt to request, unlike previously)
   - if the user has clicked "Deny" and "Never ask again" then actions which require a given permission should now give an updated justification message, and then take the user to the app settings screen directly, from where they have an opportunity to grant the permission (previously, in this scenario no justification would be seen and no opportunity to change permissions would be given, meaning the functionality - e.g. clicking LiveRide - would just do nothing).

@jezhiggins and @HilaryN, please review.

@HilaryN, is there any chance you could please do some of your thorough testing on a variety of versions, to check the behaviour is as I intended in the description above?  (I haven't got the time to test just now, but managed to squeeze in the coding herein).

Cheers.

### CODE REVIEW

**Comment by HilaryN** [comment]
Yes, will do.

**Comment by HilaryN** [comment]
Just done the first couple of tests on Adnroid 11 so far.  The second permission justification box looks good (perhaps "change this" could be "change this location permission" to be more specific?)

Seem to be having an issue with the "Ask every time" though.  After denying a few times then changing to "Ask every time", it seems to think the permission is still set to Deny.  Changing to "Allow while using this app" works OK.

When selecting "Ask every time" first time around it continues to LiveRide but doesn't ask for permission again on subsequent times using LiveRide:

[Test background location permissions 200921 Tests 1 and 2.pdf](https://github.com/cyclestreets/android/files/5255596/Test.background.location.permissions.200921.Tests.1.and.2.pdf)

**Comment by HilaryN** [comment]
Just attaching a screenshot of the second box which comes up after denying, for the others to see:

Screenshot_1600695000

**Comment by HilaryN** [comment]
I occasionally get slightly weird things happen which I can't then reproduce.  One example I've had a couple of times today is that CycleStreets location permission isn't appearing in the general Settings even though it has been set.  Here I had set it to ask every time but it's not appearing in the Settings (first 2 screenshots).  You can see it in the last screenshot (I didn't change it here, this is the screen which appeared after clicking OK on the permissions justification box):

CycleStreets permission not in settings

It's happening again now.  I've set it to "Allow while using the app" so LiveRide works fine, but I have no way of going in to the settings to change it to "Deny", for example.  I guess this is an Android problem rather than a problem with the app.

**Comment by HilaryN** [comment]
I slightly misunderstood the "Ask every time" - it only asks again if the app is closed and opened again.  (I do this by tapping the tiles / little square button at the bottom and going to the "Clear All" to close it, then tapping on the app icon again.)

There is still a slight issue where we can't tell if the user has changed the permission to "Ask every time" when we take them to settings.  As far as the app is concerned, we only know if permission is granted or denied.  "Ask every time" returns "Permission denied".
I guess we can assume that if they tap on the LiveRide button again after denying twice then it's OK to ask them again and we can maybe clear out the logPermissionAsRequested and start again.

**Comment by oliverlockwood** [comment]
After some local emulator testing (only on API 29 - I didn't have time for more), I've made some changes, including rendering out a friendly description of the permission we're requesting, and improving layout etc.

See screenshot below for an example rendering of this, and `strings.xml` for the full details for each permission type.
@HilaryN regarding the edge case you describe, I think it's probably just fine as it is - if a user keeps on trying to use a part of the app which requires an additional permission, it's reasonable to keep on giving them the option (at that point) to upgrade the permissions they've granted to the app.

Screen Shot 2020-09-24 at 16 06 46

In my view this PR is ready to go now.  @jezhiggins can you please review when you have the chance?

**Comment by oliverlockwood** [comment]
P.S. Thank you @HilaryN for your testing, it has been very helpful

**Comment by mvl22** [comment]
That text looks good.

You could optionally add to the end of the last paragraph:

"This can be independently verified as our app is open source."

**Comment by oliverlockwood** [comment]
@mvl22 I've incorporated your suggestion.

I'm going to go ahead and merge this now.  Next steps:
- @jezhiggins please feel free to add any retrospective feedback when you get to this.
- @swattor once a few hours have passed (to allow the new beta build to be accessible on the Play store), please download it and confirm whether or not the change has fixed your issue.
- I will do some testing with my phone as it is (running Android 10) and then allow the upgrade to Android 11 which it's been nagging me about for the past few days, and then I'll test again.

**Pull request merged**
