### PR TITLE
changed speak() to cancel any voice instructions already queued

### PR DESCRIPTION
**Pull request by dan424gg**
Allows voice instructions to be canceled halfway through speaking to allow more accurate voice instructions.

On a subsequent call of the speak() method, the queue of voice instructions is completely cleared.

### CODE REVIEW

**Review by oliverlockwood — COMMENTED** [review]
Thanks for the PR.

My concern would be if a "continue xxx metres" message overrode a "turn left into xxx" message and essential information got lost.

Can it be changed to "flush all except the last message and the new one I'm adding"? I'm not necessarily saying we should do this, but it would be good to have that option if testing proves it necessary.

Either way, this'll definitely need testing thoroughly in the beta!

**Comment by dan424gg** [comment]
With the most recent commit, you can mark a speak() call with an "important" parameter to override whatever is being said, and when it's not important it will just go into the queue.

I determined if a message is important if it tells any immediate or noteworthy instructions (ie. turn left in 200 meters, destination is on the left, etc) and any others are not important

**Comment by dan424gg** [comment]
And I'm sorry if any of this is unprofessional or not following any standards, this is my first pull request for an open source project!

**Comment by HilaryN** [comment]
No worries, @dan424gg .

It looks like the build has failed and I'm not sure if it's because of the Java version at your end or because it needs changing in Travis. @jezhiggins ? (As I know you changed the Java version recently :-) )

**Comment by HilaryN** [comment]
I'm adding: fixes #538 (this links it to the issue)

**Comment by jezhiggins** [comment]
> No worries, @dan424gg .
> 
> It looks like the build has failed and I'm not sure if it's because of the Java version at your end or because it needs changing in Travis. @jezhiggins ? (As I know you changed the Java version recently :-) )

It's a unit test failure in `LiveRideVoiceTest`, because we're now passing QUEUE_FLUSH in some cases instead of QUEUE_ADD. The tests just need be updated to match the new behaviour. 

Hi @dan424gg!

**Comment by dan424gg** [comment]
> > No worries, @dan424gg .
> > It looks like the build has failed and I'm not sure if it's because of the Java version at your end or because it needs changing in Travis. @jezhiggins ? (As I know you changed the Java version recently :-) )
> 
> It's a unit test failure in `LiveRideVoiceTest`, because we're now passing QUEUE_FLUSH in some cases instead of QUEUE_ADD. The tests just need be updated to match the new behaviour.
> 
> Hi @dan424gg!

Ahh I see I'll fix that! I tried looking for test files and couldn't find them, but I found them now!

**Comment by dan424gg** [comment]
I think I've changed the test cases and everything works now!

**Comment by HilaryN** [comment]
Apologies for the delay, @dan424gg.  One of us will try and get to it as soon as we can.  Hopefully I can manage it next weekend.

**Comment by dan424gg** [comment]
No worries! Thank you so much!

**Review by HilaryN — APPROVED** [review]
All good, thanks.

**Comment by HilaryN** [comment]
Note to self: will need to update whatsnew.

**Comment by HilaryN** [comment]
I wanted to test this in an emulator but for some reason the sound in my emulators didn't work for the app.  I think it may be a permissions thing but it wouldn't allow me to set the permission.
My bike is out of action (waiting for a new tyre to be delivered tomorrow), but in the end I installed it on my phone, went out on the street, and scampered up and down to get ahead of the instructions (in the dark).  I must have looked such a sight! :-() :-)

**Pull request merged**
