### PR TITLE
Prepare release notes for launching version 3.7

### PR DESCRIPTION
**Pull request by oliverlockwood**
In my view we're in a good state to get 3.7 out the door.  Once this is approved and merged, I'll perform the remaining steps to get this done.

### CODE REVIEW

**Comment by mvl22** [comment]
Is this in the beta store now?

**Comment by oliverlockwood** [comment]
@mvl22 version 3.7 is now in the main play store.
Beta version is now 3.8 (no changes above production release at present.)

**Comment by mvl22** [comment]
Great.

Can you just confirm again the minimum Android version that people need for this release?

**Comment by mvl22** [comment]
Ah sorry, looks like it's Android 6.0:

https://github.com/cyclestreets/android/blob/master/build.gradle#L13-L29

**Comment by mvl22** [comment]
Release now tweeted:
https://twitter.com/cyclestreets/status/1256641624018477056

**Pull request merged**
