### PR TITLE
Add German translation to core. #171

### PR DESCRIPTION
**Pull request by florian-f**

### CODE REVIEW

**Comment by florian-f** [comment]
https://github.com/cyclestreets/android/issues/171

**Comment by oliverlockwood** [comment]
Hi @florian-f - thanks for your submission.  Unfortunately this PR is incomplete and only translates one of 6 localisable files.  Please would you do the rest?

Additionally, please run `./gradlew lint` in the root of your repo and ensure that the build is passing before you push your changes.

Many thanks!

**Comment by oliverlockwood** [comment]
Closing as incomplete and no sign of being updated after 2 weeks.

**Comment by dekarl** [comment]
@florian-f If you don't mind I'll copy your strings into https://www.transifex.com/cyclestreets/cyclestreets-android/viewstrings/#de/lib-core-strings/99882125 so your translation work is not lost.

**Pull request closed without merging**
