### PR TITLE
Italian translation added #171

### PR DESCRIPTION
**Pull request by mikylucky**
#171

### CODE REVIEW

**Comment by oliverlockwood** [comment]
Hi @mikylucky, thanks for submitting this pull request! 

Can you please remove all the XML blocks which are marked with the attribute `translatable="false"`?

There should not be translations of these, and including them makes the build fail.

Thanks!

**Comment by mikylucky** [comment]
Now should be ok!

**Comment by mikylucky** [comment]
Now is ok ;)

**Comment by oliverlockwood** [comment]
Nice work - thank you!

**Pull request merged**
