### PR TITLE
The Great Icons Upgrade

### LINKED ISSUE #366: Use new vector images for directions
Follows on from #363, alongside with @si-the-pie was kind enough to upload a bunch of vector assets for our direction arrows etc.  These can be found in the `/assets/directions` folder of the repo.

This ticket covers making use of those in the codebase and removing the old density-independent bitmaps.

### PR DESCRIPTION
**Pull request by oliverlockwood**
Now ready for review.  Comprising the following key areas:
### Iconics:
*Upgrading the Iconics libraries to latest
* Moving away from deprecated usage of IconicsContextWrapper (see mikepenz/Android-Iconics#470)
* Replacing some more blurry old icons with Material design ones from the Iconics library
* Refactoring the `IconicsHelper` methods for more concise usage

### And the rest:
* Replacing all the navigation icons used in LiveRide with @si-the-pie's new vector ones (closes #366)
* Adding versions of the compass icons for use in different pixel density screens
* Moving a bunch of SVG images which are unused, but may be useful for reference, out into the root `assets` folder, so as not to be part of the packaged app
* Removing a whole lot of unused images
* Changing a couple of classes from Java to Kotlin
* Removing the unused `osmarender` / `rendertheme` stuff - I believe this is a hangover from when we used to package the Mapsforge library instead of including it as a dependency

### Added since PR was originally raised:
* Making POI icons less blurry (towards #402)
* Bug identified and fixed: POI category list view had gone a bit mental when re-entered after previously selecting something
* Icons added to the root Settings screen (see screenshot at the bottom)

## Descriptive screenshots
The only thing that can be considered a _change_ instead of purely an _improvement_ is my decision to replace the lock-screen-on button, from just being an open padlock, to this:
Screen Shot 2020-05-17 at 16 35 51

New icons on the Settings screen are shown here:
Screen Shot 2020-05-18 at 16 36 24

### CODE REVIEW

**Comment by mvl22** [comment]
Sounds great!

I'll look forward to testing this tomorrow (I have a new second-hand Android 9 device arriving, for testing purposes!)

**Comment by mvl22** [comment]
Does this automatically result in a new build in Google Play appearing on the phone?

**Comment by oliverlockwood** [comment]
Thanks @jezhiggins.

@mvl22 after being merged the artifact goes straight to Google Play, but in my experience it normally takes a few hours before it appears as an available update to a phone which is on the Beta programme.  Speaking personally, I merged this 4 hours ago, and have been pinging the Play store intermittently since, and it's only just appeared to me as available.  (But it may be made available in blocks to different ranges of user IDs; I don't know what Google does under the covers here.)

But it's worth you refreshing the Play Store now and taking a look.

**Comment by mvl22** [comment]
OK, so just to be clear, this happens automatically:

Push to master -> Automated build -> Google Play beta store

**Comment by oliverlockwood** [comment]
@mvl22 yes. I think we've been over this a few times now... 🙂

**Pull request merged**
