### PR TITLE
Migrate `register()`, `signin()`, and `sendFeedback()` APIs to Retrofit

### PR DESCRIPTION
**Pull request by oliverlockwood**
Similar to the other PRs I've raised recently.

A couple of things to note:
-  As part of migrating each of these, I've also upgraded to use the V2 API.
-  I haven't been able to integration-test the new implementation of the signin() API, due to #138.  If this can't be resolved swiftly, could you let me have a test email and password so I can verify this aspect?

### CODE REVIEW

**Comment by oliverlockwood** [comment]
@mvl22 @jezhiggins another iteration of the Retrofit migration for review when you get the chance, if you don't mind.  Hope Wednesday's treating you both well.

**Comment by mvl22** [comment]
More great work, Oliver - thanks.

I notice that this includes some tests (great) but that these seem to test comparison of the `test` key's value, as in
libraries/cyclestreets-core/src/test/resources/__files/registration-error.json
libraries/cyclestreets-core/src/test/resources/__files/registration-ok.json

Please be aware that, as documented, the string values that the API responds with may in future vary. For instance, when we shift the API to having internationalisation support that will definitely change.

So, to be safe, I would test for the presence of a non-empty string, or indeed just the presence of a key called `test` which should be enough to verify a test.

**Comment by oliverlockwood** [comment]
Glad to help out 👍 

@jezhiggins - Thanks for merging.

@mvl22 Can you clarify your concern?  [RetrofitApiClientTest](https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/test/java/net/cyclestreets/api/client/RetrofitApiClientTest.java) (the only place where [registration-ok.json](https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/test/resources/__files/registration-ok.json) and [api-error.json](https://github.com/cyclestreets/android/blob/master/libraries/cyclestreets-core/src/test/resources/__files/api-error.json) are used) is a unit test so effectively the tests verify:
-  that whatever the server returns (in this case mocked by Wiremock) is propagated through the system
-  hardcoded strings in the app itself
I believe therefore that those tests are robust to changes in the string values returned by the server.

If I've misunderstood, please accept my apologies and point me more specifically at what needs changing 😀

**Comment by mvl22** [comment]
Ah, thanks for the clarification!

**Pull request merged**
