### PR TITLE
Add German translations provided on Transifex

### PR DESCRIPTION
**Pull request by oliverlockwood**
It turns out German translations had been provided on Transifex, so let's add them to the project.

This can't be merged yet as a few of the translations are incomplete. (It's our own fault, because the source files on Transifex were a long way out of date.)

@rugk Lint gives me the following errors.  Since you were kind enough to provide some of the German translation, can you please submit translations for these outstanding strings, either to Transifex once the source files are updated, or directly on this PR if that's easier?

libraries/cyclestreets-view/src/main/res/values/strings.xml:47: "photo_could_not_load_categories" is not translated in "de" (German)
libraries/cyclestreets-fragments/src/main/res/values/strings.xml:38: "ic_menu_liveride" is not translated in "de" (German)
libraries/cyclestreets-fragments/src/main/res/values/strings.xml:39: "ic_menu_stopride" is not translated in "de" (German)
libraries/cyclestreets-fragments/src/main/res/values/strings.xml:41: "hello_blank_fragment" is not translated in "de" (German)
libraries/cyclestreets-fragments/src/main/res/values/strings.xml:53: "about_version_default" is not translated in "de" (German)
libraries/cyclestreets-fragments/src/main/res/values/strings.xml:59: "itinerary_segment_time" is not translated in "de" (German)

Note that this issue was highlighted while looking at the out-of-date references in Transifex, as part of https://github.com/cyclestreets/android/pull/175#issuecomment-394266665.

### CODE REVIEW

**Comment by rugk** [comment]
I see no untranslated strings in Transifex:

grafik

**Comment by oliverlockwood** [comment]
Hi @rugk - you're looking at one specific resource file which is fully translated.  There are 6 resource files in total; two of them have at least one untranslated string.

My view as a project admin is slightly different, but I suspect that if you press the back button - looks like a `<` - in the top left, then you'll be able to find the other resource files.  Let me know how you get on 😃

**Comment by rugk** [comment]
done

**Comment by oliverlockwood** [comment]
Thanks @rugk.

@jezhiggins can you please review / merge when you have the chance?  Thanks

**Comment by jezhiggins** [comment]
Thank you!

**Pull request merged**
