### PR TITLE
Hungarian translations added

### PR DESCRIPTION
**Pull request by tm4s**
refs #171

### CODE REVIEW

**Comment by oliverlockwood** [comment]
Hi @tm4s, thanks for the PR but you have only translated one of the 6 files which need localizing. Can you please do the others as well, being sure to follow the guidelines given in #171 and making sure the build passes? 

Many thanks!

**Comment by tm4s** [comment]
Hi @oliverlockwood, sure working on it!

**Comment by oliverlockwood** [comment]
@tm4s are you still working on this one?  I'm trying to close down incomplete PRs.

**Comment by oliverlockwood** [comment]
Closing this PR now as it's incomplete.  @tm4s if you come back to this with a more complete translation, feel free to re-open.  Many thanks.

**Pull request closed without merging**
